tasks:
  - init: npm install
    command: |
      gp sync-done npm-install
  - command: |
      gp sync-await npm-install
      npm run dev
  - command: |
      gp sync-await npm-install
      npm run storybook

github:
  prebuilds:
    addBadge: true

ports:
  - port: 3000
    name: next dev
    onOpen: notify
  - port: 6006
    name: storybook
    onOpen: notify

vscode:
  extensions:
    - EditorConfig.EditorConfig
    - dbaeumer.vscode-eslint
    - eamodio.gitlens
    - esbenp.prettier-vscode
    - Prisma.prisma
